package Salary;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import dbConnection.DBConnect;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dinisuru
 */
public class LeavesReport extends javax.swing.JFrame {

    /**
     * Creates new form LeavesReport
     */
    public LeavesReport() {
        initComponents();
        con = DBConnect.connect();
         Calendar today = Calendar.getInstance();    
         int day = today.get(Calendar.DATE);
         int month = today.get(Calendar.MONTH) + 1;
         int year = today.get(Calendar.YEAR);
         setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
         
            String s = year+"/"+month;
        
        String id;
        String date;
        String reason;
        
        txtprint.setText(txtprint.getText()+"************************************************************************\n");
        txtprint.setText(txtprint.getText()+"************************ Nimalsiri Book Shop ***************************\n");
        txtprint.setText(txtprint.getText()+"************************ Monthly Leaves Report **************************\n\n\n\n");
        
        
        
        int a;
        try {
        
            pst = con.prepareStatement("select empid from leaves where date like '%"+s+"%' group by empid ");
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                
                id = rs.getString("empid");
                
                txtprint.setText(txtprint.getText()+"Employee_ID = "+ id+"\n" );
                txtprint.setText(txtprint.getText()+"Employee_Name = "+ getName(id)+"\n" );
                txtprint.setText(txtprint.getText()+"                               Date                                    Reason \n" );
                
                pst1 = con.prepareStatement("select * from leaves where empid = '"+id+"%' and date like '%"+s+"%' ");
                ResultSet rss = pst1.executeQuery();
                
                ResultSetMetaData rd = rss.getMetaData();
                a = rd.getColumnCount();
                
                while(rss.next()){

                    date = rss.getString("date");
                    reason = rss.getString("reason");
         
                    txtprint.setText(txtprint.getText()+"                               "+ date+"                               "+reason+"\n" );

            }
                
                txtprint.setText(txtprint.getText()+"\n\n" );
  
            }
  
        } catch (SQLException ex) {
            Logger.getLogger(LeavesReport.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            txtprint.print();
        } catch (PrinterException ex) {
            Logger.getLogger(LeavesReport.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      
    }

    Connection con;
    PreparedStatement pst , pst1;
    DefaultTableModel df;
    
    public String getName(String id){
        
        String name = null;
        
        try {
            // TODO add your handling code here:
      
            pst = con.prepareStatement("select CONCAT(f_Name,' ',l_Name) AS name from employees where empID = '"+id+"%' and empStatus = 'active'");
            ResultSet rs = pst.executeQuery();
            
        
             while(rs.next()){
                
                name = rs.getString("name");
                
            }
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(LeavesAdd.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        return name;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtprint = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtprint.setColumns(20);
        txtprint.setRows(5);
        jScrollPane1.setViewportView(txtprint);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeavesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeavesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeavesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeavesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LeavesReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtprint;
    // End of variables declaration//GEN-END:variables
}
