/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import Salary.AdminPage;
import Salary.purchase;
import dbConnection.DBConnect;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hansab
 */
public class InventoryDisplay extends javax.swing.JFrame {

    /**
     * Creates new form InventoryDisplay
     */
    public InventoryDisplay() {
        initComponents();
        con = DBConnect.connect();
        load();
        suplier();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }

    
        Connection con;
        PreparedStatement pst;
        DefaultTableModel df;
        ResultSet rs;
        
        
         
        
        public void load()
        {
            int a;
        try {
            pst = con.prepareStatement("select * from inventory");
            ResultSet rs = pst.executeQuery();
            
            ResultSetMetaData rd = rs.getMetaData();
            a = rd.getColumnCount();
            df = (DefaultTableModel)jTable1.getModel();
            df.setRowCount(0);
            
            while(rs.next())
            { 
                Vector v2 = new Vector();
                for(int i=1 ; i<=a ; i++)
                {
                    v2.add(rs.getString("id"));
                    v2.add(rs.getString("ItemCode"));
                    v2.add(rs.getString("itemName"));
                    v2.add(rs.getString("description"));
                    v2.add(rs.getString("itemQty"));
                    v2.add(rs.getString("itemType"));
                    v2.add(rs.getString("costPrice"));
                    v2.add(rs.getString("sellPrice"));
                    v2.add(rs.getString("supplier"));
                }
                df.addRow(v2);
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(InventoryDisplay.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
        }
        
        public void suplier(){
        
        try {
            pst = con.prepareStatement("select Distinct name from supplier");
            rs = pst.executeQuery();
            
            txtvendor.removeAllItems();
            
            while(rs.next()){
                
                txtvendor.addItem(rs.getString("name"));
                
            }
          
                    } catch (SQLException ex) {
            Logger.getLogger(purchase.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
        
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        desctxt = new javax.swing.JTextField();
        nametxt = new javax.swing.JTextField();
        cpricetxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        itypetxt = new javax.swing.JTextField();
        spricetxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnadd = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        qtytxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtvendor = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        itmcode = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        search = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Item Name");

        jLabel3.setText("Descrition");

        jLabel4.setText("Quantity");

        jLabel5.setText("Cost price");

        nametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametxtActionPerformed(evt);
            }
        });
        nametxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nametxtKeyReleased(evt);
            }
        });

        cpricetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpricetxtActionPerformed(evt);
            }
        });
        cpricetxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cpricetxtKeyReleased(evt);
            }
        });

        jLabel7.setText("Item Type");

        itypetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itypetxtActionPerformed(evt);
            }
        });

        spricetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spricetxtActionPerformed(evt);
            }
        });
        spricetxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                spricetxtKeyReleased(evt);
            }
        });

        jLabel6.setText("Selling Price");

        btnadd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnadd.setText("Add");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("Deselect");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        qtytxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                qtytxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qtytxtKeyReleased(evt);
            }
        });

        jLabel8.setText("Suplier");

        jLabel9.setText("Item code");

        itmcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmcodeActionPerformed(evt);
            }
        });
        itmcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                itmcodeKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 0));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 0));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 51, 0));

        jButton6.setBackground(new java.awt.Color(204, 51, 0));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setText("Home");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(204, 255, 204));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setText("Purchase");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(desctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(27, 27, 27))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(349, 349, 349))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel5))
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(spricetxt)
                                    .addComponent(cpricetxt)
                                    .addComponent(txtvendor, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(itypetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                    .addComponent(btnadd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(77, 77, 77)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(itmcode)
                                    .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(qtytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jButton6)
                .addGap(96, 96, 96)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(itmcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(qtytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(itypetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cpricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(spricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtvendor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnadd)
                            .addComponent(jButton2))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton5))))
                .addGap(62, 62, 62)
                .addComponent(jButton7)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Inventory");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Item ID", "Item Name", "Description", "Quantity", "Item Type", "Cost Price", "Selling Price", "Supplier"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });

        jLabel14.setText("Search By Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200)
                        .addComponent(jLabel1)
                        .addContainerGap(485, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametxtActionPerformed

    private void cpricetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpricetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpricetxtActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

            itmcode.setText("");
            nametxt.setText("");
            desctxt.setText("");
            qtytxt.setText("");
            itypetxt.setText("");
            cpricetxt.setText("");
            spricetxt.setText("");
            nametxt.requestFocus();
            load();
            
            btnadd.setEnabled(true);
            
        

       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void itypetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itypetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itypetxtActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed

        try {
            String icode = itmcode.getText();
            String iname = nametxt.getText();
            String idesc = desctxt.getText();
            String iqty = qtytxt.getText();
            String itype = itypetxt.getText();
            String cprice = cpricetxt.getText();
            String sprice = spricetxt.getText();
            String supplier = txtvendor.getSelectedItem().toString();
            
 
            pst = con.prepareStatement("insert into inventory (ItemCode,itemName,description,itemQty,itemType,costPrice,sellPrice,supplier)values(?,?,?,?,?,?,?,?)");
            pst.setString(1,icode);
            pst.setString(2,iname);
            pst.setString(3,idesc);
            pst.setString(4,iqty);
            pst.setString(5,itype);
            pst.setString(6,cprice);
            pst.setString(7,sprice);
            pst.setString(8,supplier);            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Item Added Successfull...!");
            
            nametxt.setText("");
            desctxt.setText("");
            qtytxt.setText("");
            itypetxt.setText("");
            cpricetxt.setText("");
            spricetxt.setText("");
            nametxt.requestFocus();
            load();
        
        } catch (SQLException ex) {
            Logger.getLogger(InventoryDisplay.class.getName()).log(Level.SEVERE, null, ex);
        }
            

    }//GEN-LAST:event_btnaddActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

           df = (DefaultTableModel)jTable1.getModel();
           int selected = jTable1.getSelectedRow();
           
            String itemId = df.getValueAt(selected, 1).toString();
            itmcode.setText(itemId);
            nametxt.setText(df.getValueAt(selected,2).toString());
            desctxt.setText(df.getValueAt(selected,3).toString());
            qtytxt.setText(df.getValueAt(selected,4).toString());
            itypetxt.setText(df.getValueAt(selected,5).toString());
            cpricetxt.setText(df.getValueAt(selected,6).toString());
            spricetxt.setText(df.getValueAt(selected,7).toString());
            txtvendor.addItem(df.getValueAt(selected,8).toString());
            itmcode.setEditable(true);
            btnadd.setEnabled(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        
            df = (DefaultTableModel)jTable1.getModel();
            int selected = jTable1.getSelectedRow();
           
            int iid = Integer.parseInt(df.getValueAt(selected, 0).toString());
            
            String itemid = itmcode.getText();
            String iname = nametxt.getText();
            String idesc = desctxt.getText();
            String iqty = qtytxt.getText();
            String itype = itypetxt.getText();
            String cprice = cpricetxt.getText();
            String sprice = spricetxt.getText();
            
           try { 
 
            pst = con.prepareStatement("update inventory set ItemCode=? ,itemName=? , description = ? , itemQty = ? , itemType = ? , costPrice = ? , sellPrice = ? where id = ?");
            pst.setString(1,itemid);
            pst.setString(2,iname);
            pst.setString(3,idesc);
            pst.setString(4,iqty);
            pst.setString(5,itype);
            pst.setString(6,cprice);
            pst.setString(7,sprice);
            pst.setInt(8,iid);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Item Update Successfull...!");
            
            nametxt.setText("");
            desctxt.setText("");
            qtytxt.setText("");
            itypetxt.setText("");
            cpricetxt.setText("");
            spricetxt.setText("");
            itmcode.setText("");
            itmcode.requestFocus();
            load();
            
            btnadd.setEnabled(true);
            
        } catch (SQLException ex) {
            Logger.getLogger(InventoryDisplay.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
            df = (DefaultTableModel)jTable1.getModel();
            int selected = jTable1.getSelectedRow();
           
            String itemId = df.getValueAt(selected, 0).toString();
            
            try { 
 
            pst = con.prepareStatement("delete from inventory where ItemCode = ?");
            pst.setString(1,itemId);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Item Delete Successfull...!");
            
            nametxt.setText("");
            desctxt.setText("");
            qtytxt.setText("");
            itypetxt.setText("");
            cpricetxt.setText("");
            spricetxt.setText("");
            nametxt.requestFocus();
            load();
            
            btnadd.setEnabled(true);
            
        } catch (SQLException ex) {
            Logger.getLogger(InventoryDisplay.class.getName()).log(Level.SEVERE, null, ex);
        }

        // TODO add your handling code here:

        // TODO add your handling code here:

        // TODO add your handling code here:

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void spricetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spricetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spricetxtActionPerformed

    private void qtytxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtytxtKeyReleased
       
        
        String PATTERN = "[0-9]{1,5}";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(qtytxt.getText());
        if(!match.matches()){
            jLabel10.setText("Please use Numbers");
        }
        else{
            jLabel10.setText(null);
        }
        
        
        
    }//GEN-LAST:event_qtytxtKeyReleased

    private void qtytxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtytxtKeyPressed
        // TODO add your handling code here:
        
      
            
    }//GEN-LAST:event_qtytxtKeyPressed

    private void cpricetxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpricetxtKeyReleased
      
          
        String PATTERN = "[0-9]+([,.][0-9]{1,2})?";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(cpricetxt.getText());
        if(!match.matches()){
            jLabel11.setText("please use Numbers");
        }
        else{
            jLabel11.setText(null);
        }
    }//GEN-LAST:event_cpricetxtKeyReleased

    private void spricetxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spricetxtKeyReleased
             
        String PATTERN = "[0-9]+([,.][0-9]{1,2})?";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(spricetxt.getText());
        if(!match.matches()){
            jLabel12.setText("please use Numbers");
        }
        else{
            jLabel12.setText(null);
        }
    }//GEN-LAST:event_spricetxtKeyReleased

    private void itmcodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itmcodeKeyReleased
        /*  
        if(itmcode.getText().trim().isEmpty()){
            jLabel13.setText("This cant be null");
        }
        else{
            jLabel13.setText(null);
        } */
    
      String PATTERN ="[a-zA-Z][a-zA-Z][0-9]{1,5}";
      Pattern patt = Pattern.compile(PATTERN);
      Matcher match = patt.matcher(itmcode.getText());
      if(!match.matches()){
          jLabel13.setText("Item code is invalid");
      }
      else{
          jLabel13.setText(null);
      }
      
    }//GEN-LAST:event_itmcodeKeyReleased

    private void nametxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nametxtKeyReleased
        
        /*String val =nametxt.getText().toString();
        
        int a ;
        
        try{
                pst = con.prepareStatement("select * from inventory where itemName like '%"+val+"%'");
                ResultSet rs = pst.executeQuery();
                
                ResultSetMetaData rd = rs.getMetaData();
                a = rd.getColumnCount();
                df = (DefaultTableModel) jTable1.getModel();
                df.setRowCount(0);
                
                while(rs.next()){
                    
                    Vector v2 = new Vector();
                    for(int i =1; i<=a ; i++)
                    {
                        v2.add(rs.getString("Itemcode"));
                        v2.add(rs.getString("itemName"));
                        v2.add(rs.getString("description"));
                        v2.add(rs.getString("itemQty"));
                        v2.add(rs.getString("itemType"));
                        v2.add(rs.getString("costPrice"));
                        v2.add(rs.getString("sellPrice"));
                    
                    }
                    df.addRow(v2);
                
                
                }
        
        } catch (SQLException ex) {
            Logger.getLogger(InventoryDisplay.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_nametxtKeyReleased

    private void itmcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmcodeActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        // TODO add your handling code here:
        
        String val =search.getText().toString();
        
        int a ;
        
        try{
                pst = con.prepareStatement("select * from inventory where itemName like '%"+val+"%'");
                ResultSet rs = pst.executeQuery();
                
                ResultSetMetaData rd = rs.getMetaData();
                a = rd.getColumnCount();
                df = (DefaultTableModel) jTable1.getModel();
                df.setRowCount(0);
                
                while(rs.next()){
                    
                    Vector v2 = new Vector();
                    for(int i =1; i<=a ; i++)
                    {
                        v2.add(rs.getString("id"));
                        v2.add(rs.getString("Itemcode"));
                        v2.add(rs.getString("itemName"));
                        v2.add(rs.getString("description"));
                        v2.add(rs.getString("itemQty"));
                        v2.add(rs.getString("itemType"));
                        v2.add(rs.getString("costPrice"));
                        v2.add(rs.getString("sellPrice"));
                        v2.add(rs.getString("supplier"));
                    
                    }
                    df.addRow(v2);
                
                
                }
        
        } catch (SQLException ex) {
            Logger.getLogger(InventoryDisplay.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_searchKeyReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:

        AdminPage ap = new AdminPage();
        ap.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
        purchase pu = new purchase();
        pu.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JTextField cpricetxt;
    private javax.swing.JTextField desctxt;
    private javax.swing.JTextField itmcode;
    private javax.swing.JTextField itypetxt;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nametxt;
    private javax.swing.JTextField qtytxt;
    private javax.swing.JTextField search;
    private javax.swing.JTextField spricetxt;
    private javax.swing.JComboBox<String> txtvendor;
    // End of variables declaration//GEN-END:variables
}
